export const user = [
  {
    userid: 'SFIN2102',
    firstName: 'Sourabh',
    lastName: 'Jain',
    email: 'jainsourabh@gmail.com',
    contact: '9493812562',
    address: 'Galaxy Apartments, indore',
    rolekey: 2,
  },
  {
    userid: 'SFIN3103',
    firstName: 'Prakhar',
    lastName: 'Bhatele',
    email: 'prkhrbhatele@gmail.com',
    contact: '7953457867',
    address: 'Silicon city, ujjain',
    rolekey: 3,
  },
  {
    userid: 'SFIN2104',
    firstName: 'Gaurav',
    lastName: 'Sen',
    email: 'gksen@gmail.com',
    contact: '9249051932',
    address: 'Vasant Vihar, Bhopal',
    rolekey: 2,
  },
  {
    userid: 'SFIN3104',
    firstName: 'Harsh',
    lastName: 'Talreja',
    email: 'harsh.T@gmail.com',
    contact: '7463892762',
    address: 'Tansen Nagar, Gwalior',
    rolekey: 3,
  },
  {
    userid: 'SFIN1106',
    firstName: 'hardik',
    lastName: 'jain',
    email: 'hardik997jain@gmail.com',
    contact: '8623487127',
    address: 'Sector 125 , Noida',
    rolekey: 1,
  },
  {
    userid: 'SFIN1101',
    firstName: 'Utkarsh',
    lastName: 'Sharma',
    email: 'utkarsh.sharma@gmail.com',
    contact: '7247051932',
    address: '574 Mukherjee Nagar, Dewas',
    rolekey: 1,
  },
];
